### ISSUE TITLE
Gate Opener

### ISSUE THREAD

**Issue by jonflores1093** [jonflores1093/ThirdPersonDesignScenerios#2]
_**Main Idea:**_ Under the scene "ExampleScene" in the Contexual-Message-trigger-branch,  I wanted to demonstrate a gate opening when the player steps into the trigger zone and close when the player steps out of the trigger zone.

_**Problem:**_ When the player walks into the trigger, the gate opens and closes without ever stopping at the open state when the player is still in the trigger.

**Comment by dantogno** [comment]
- You should name things more clearly. It is not clear that ShortWall is the door / gate.
- The directional light is creating a shadow that makes it too hard to see anything. Adjust it's rotation or add more lighting.
- There is a runtime error with your SpawnManager script because you are trying to execute functions that can only be called inside of functions. You need to do this initialization behavior inside of the Start function, not just floating at the top of your class.
- The reason the gate bug is happening is that you have the trigger attached to the object that is moving up. This means the trigger moves up with the gate. That causes the player to exit the trigger as the player is left on the ground and the trigger raises  into the air.
